server:
  port: 8082

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_cart
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cart-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ecommerce.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET:verySECURE_secrettHAT_should_BE_CHANGED_in_production890123456789012345678901234567890}
  issuer: ecommerce-auth-service

# Configuração gRPC
grpc:
  client:
    catalog-service:
      address: static://localhost:9090
      negotiation-type: plaintext
    auth-service:
      address: static://localhost:9091
      negotiation-type: plaintext
  server:
    port: 9092

# Configuração de cache
cache:
  ttl:
    cart: 30 # tempo em minutos

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html 