# Configurações do Servidor
server:
  port: 8085
  servlet:
    context-path: /

# Configurações do Spring
spring:
  application:
    name: payment-service
  
  # Configurações do banco de dados
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Configurações JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Configurações do Flyway
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Configurações de Segurança
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8084/
          jwk-set-uri: http://auth-service:8084/api/auth/jwks

# Configurações do Logging
logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR

# Configurações da API
api:
  version: 1.0.0

# Configurações do Stripe
stripe:
  api:
    key: ${STRIPE_API_KEY:sk_test_51TestKey}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_test_secret}

# Configurações de integração com outros serviços
services:
  order:
    host: order-service
    port: 8082
  user:
    host: user-service
    port: 8084

# Configurações do Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Configurações de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    app:
      name: ${spring.application.name}
      version: ${api.version} 